#!/bin/sh

RULESDIR="$(cd "$(dirname "$0")" && pwd)"
RULESPATH=$RULESDIR/by-rules
ipt=$(command -v iptables-legacy || command -v iptables)
ip6t=$(command -v ip6tables-legacy || command -v ip6tables)
IPT_M="$ipt -t mangle -w"
IPT_N="$ipt -t nat -w"
IP6T_M="$ipt -t mangle -w"
IP6T_N="$ipt -t nat -w"
[ -z "$ip6t" -o -z "$(lsmod | grep 'ip6table_nat')" ] && IP6T_N="eval #$IP6T_N"
[ -z "$ip6t" -o -z "$(lsmod | grep 'ip6table_mangle')" ] && IP6T_M="eval #$IP6T_M"

FWI=$(uci -q get firewall.bypass.path) || FWI=/tmp/etc/bypass.include
LFILE=/tmp/by_local.ipset
LOG=/tmp/log/bypass.log
TAG="_SS_SPEC_RULE_"
MODE=0
DEBUG=''
loger() {
	# 1.alert 2.crit 3.err 4.warn 5.notice 6.info 7.debug
	logger -st BYPASS[$$] -p$1 $2
}
log(){
	echo "$(date +'%Y-%m-%d %H:%M:%S') $*" >> $LOG
}


	flush_iptables() {
		local ipts="$ipt -t $1"
		local DAT=$($ipt-save -t $1)
		eval $(echo "$DAT" | grep "$TAG" | sed -e 's/^-A/$ipts -D/' -e 's/$/;/')
		for X in $(echo "$DAT" | awk '/^:SS_SPEC/{print $1}'); do
			$ipts -F ${X:1} 2>/dev/null && $ipts -X ${X:1}
		done
	}

flush_dns(){
	while ${IP6T_N} -D PREROUTING -p $1 --dport 53 -m comment --comment $TAG -j REDIRECT --to-ports 53 2>/dev/null;do :;done
}

flush_r(){
	flush_iptables nat
	flush_iptables mangle
	flush_dns udp
	flush_dns tcp
	while ip rule del fwmark 1 lookup 100 2>/dev/null;do :;done
	ip route del local 0.0.0.0/0 dev lo table 100 2>/dev/null
	ipset -X ss_spec_lan_ac 2>/dev/null
	ipset -X ss_spec_wan_ac 2>/dev/null
	ipset -X fplan 2>/dev/null
	ipset -X gmlan 2>/dev/null
	ipset -X oversea 2>/dev/null
	ipset -X blacklist 2>/dev/null
	ipset -X netflix 2>/dev/null
	ipset -X china_v4 2>/dev/null
	ipset -X china_v6 2>/dev/null
	ipset -X by_all 2>/dev/null
	[ -n "$FWI" ] && echo '#!/bin/sh' >$FWI
}

ipset_r(){
	${IPT_N} -N SS_SPEC_WAN_FW || return 1
	${IPT_N} -A SS_SPEC_WAN_FW -p tcp $PROXY_PORTS -j REDIRECT --to-ports $local_port 2>/dev/null
	[ $MODE = oversea ] && B=1
	[ $MODE = router -o $MODE = all ] && [ -z "$PROXY_PORTS" ] && B=1
	[ -n "$NF_SERVER" ] && ipset -N netflix hash:net 2>/dev/null
	if [ $MODE != all ];then
		[ -n "$LAN_FP_IP" ] && ipset -N fplan hash:net 2>/dev/null
		[ -n "$WAN_FW_IP" -o $MODE != router -o -s /etc/bypass/black.list ] && ipset -N blacklist hash:net 2>/dev/null
		for ip in $LAN_FP_IP;do ipset -! add fplan $ip;done
		for ip in $WAN_FW_IP;do ipset -! add blacklist $ip;done
	fi
	if [ -n "$LAN_GM_IP" -a ! "$B" ];then
		C=1
		ipset -N gmlan hash:net 2>/dev/null
		for ip in $LAN_GM_IP;do ipset -! add gmlan $ip;done
	fi
	[ "$A" -o "$C" ] && /usr/share/bypass/chinaipset
	[ $MODE = router ] && /usr/share/bypass/chinaipset v6
	cat > $LFILE  <<EOF
0.0.0.0/8
10.0.0.0/8
100.64.0.0/10
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.0.0.0/24
192.0.2.0/24
192.88.99.0/24
192.168.0.0/16
198.18.0.0/15
198.51.100.0/24
203.0.113.0/24
224.0.0.0/4
240.0.0.0/4
EOF
	sed -i 's/^/add ss_spec_wan_ac /' $LFILE 
	sed -i '1i\create ss_spec_wan_ac hash:net' $LFILE 
	ipset -F ss_spec_wan_ac 2>/dev/null
	ipset -R < $LFILE  2>/dev/null
	rm -f $LFILE 
	for ip in $WAN_BP_IP;do ipset -! add ss_spec_wan_ac $ip;done
	${IPT_N} -N SS_SPEC_WAN_AC
	${IPT_N} -A SS_SPEC_WAN_AC -d $server -j RETURN
	${IPT_N} -A SS_SPEC_WAN_AC -m set --match-set ss_spec_wan_ac dst -j RETURN
	if ipset list netflix >/dev/null 2>&1;then
		[ "$(uci -q get bypass.@global[0].nf_proxy)" = 1 ] && ${IPT_N} -A SS_SPEC_WAN_AC -d $NF_SERVER -j SS_SPEC_WAN_FW || ipset -! add ss_spec_wan_ac $NF_SERVER
		${IPT_N} -A SS_SPEC_WAN_AC -p tcp -m set --match-set netflix dst -j REDIRECT --to-ports $NF_PORT
	fi
	${IPT_N} -A SS_SPEC_WAN_AC -m set --match-set ss_spec_wan_ac dst -j RETURN
	ipset list fplan >/dev/null 2>&1 && ${IPT_N} -A SS_SPEC_WAN_AC -m set --match-set fplan src -j SS_SPEC_WAN_FW
	ipset list blacklist >/dev/null 2>&1 && ${IPT_N} -A SS_SPEC_WAN_AC -m set --match-set blacklist dst -j SS_SPEC_WAN_FW
	ipset list gmlan >/dev/null 2>&1 && ${IPT_N} -A SS_SPEC_WAN_AC -m set --match-set gmlan src -m set ! --match-set china_v4 dst -j SS_SPEC_WAN_FW

	case $MODE in
		router)${IPT_N} -A SS_SPEC_WAN_AC -m set ! --match-set china_v4 dst -j SS_SPEC_WAN_FW;;
		oversea)
		      ipset -N oversea hash:net 2>/dev/null
		      ${IPT_N} -I SS_SPEC_WAN_AC -m set --match-set oversea dst -j SS_SPEC_WAN_FW
		      ${IPT_N} -A SS_SPEC_WAN_AC -m set --match-set gmlan src -j SS_SPEC_WAN_FW
		      ${IPT_N} -A SS_SPEC_WAN_AC -m set --match-set china_v4 dst -j SS_SPEC_WAN_FW
		      ;;
		all)${IPT_N} -A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW;;
	esac

	if [ "$LAN_AC_IP" ];then
		ipset -! -R <<-EOF || return 1
		create ss_spec_lan_ac hash:net
		$(for ip in ${LAN_AC_IP:1};do echo "add ss_spec_lan_ac $ip";done)
EOF
		case "${LAN_AC_IP:0:1}" in
			w|W)MATCH_SET="-m set --match-set ss_spec_lan_ac src";;
			b|B)MATCH_SET="-m set ! --match-set ss_spec_lan_ac src";;
		esac
	fi

	${IPT_N} -I PREROUTING 1 -p tcp $MATCH_SET -m comment --comment "$TAG" -j SS_SPEC_WAN_AC
	if [ $y ];then
		${IPT_N} -I PREROUTING 1 -p udp --dport 53 -m comment --comment $TAG -j REDIRECT --to-ports 53
		${IPT_N} -I PREROUTING 2 -p tcp --dport 53 -m comment --comment $TAG -j REDIRECT --to-ports 53
		[ -n "$ip6t" ] && ${IP6T_N} -I PREROUTING 1 -p udp --dport 53 -m comment --comment $TAG -j REDIRECT --to-ports 53
		[ -n "$ip6t" ] && ${IP6T_N} -I PREROUTING 2 -p tcp --dport 53 -m comment --comment $TAG -j REDIRECT --to-ports 53
	fi
	${IPT_N} -I OUTPUT 1 -p tcp -m comment --comment "$TAG" -j SS_SPEC_WAN_AC
}

dns_hijack() {
	$ipt_n -I SS_SPEC__TPROXY -p udp --dport 53 -j REDIRECT --to-ports 53
}
tp_rule(){
	[ -n "$SERVER" ] || return 0
	ip rule add fwmark 1 lookup 100
	ip route add local 0.0.0.0/0 dev lo table 100
	${IPT_M} -N SS_SPEC_TPROXY
	if ipset list china_v4 >/dev/null 2>&1;then
		[ $MODE = oversea ] && a= || a=!
		# error  
		${IPT_M} -A SS_SPEC__TPROXY -p udp -m set $a --match-set china_v4 dst --dport 80 -j DROP
		${IPT_M} -A SS_SPEC__TPROXY -p udp -m set $a --match-set china_v4 dst --dport 443 -j DROP
	elif ipset list blacklist >/dev/null 2>&1;then
	# error  
		${IPT_M} -A SS_SPEC__TPROXY -p udp -m set --match-set blacklist dst --dport 80 -j DROP
		${IPT_M} -A SS_SPEC__TPROXY -p udp -m set --match-set blacklist dst --dport 443 -j DROP
	fi
	${IPT_M} -A SS_SPEC_TPROXY -p udp --dport 53 -j RETURN
	${IPT_M} -A SS_SPEC_TPROXY -p udp -d $SERVER -j RETURN
	${IPT_M} -A SS_SPEC_TPROXY -p udp -m set --match-set ss_spec_wan_ac dst -j RETURN
	ipset list fplan >/dev/null 2>&1 && ${IPT_M} -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set --match-set fplan src -j TPROXY --on-port $LOCAL_PORT --tproxy-mark 0x1/0x1
	ipset list blacklist >/dev/null 2>&1 && ${IPT_M} -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set --match-set blacklist dst -j TPROXY --on-port $LOCAL_PORT --tproxy-mark 0x1/0x1
	ipset list gmlan >/dev/null 2>&1 && ${IPT_M} -A SS_SPEC_TPROXY -p udp -m set --match-set gmlan src -m set ! --match-set china_v4 dst -j TPROXY --on-port $LOCAL_PORT --tproxy-mark 0x1/0x1

	case $MODE in
		router)${IPT_M} -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set ! --match-set china_v4 dst -j TPROXY --on-port $LOCAL_PORT --tproxy-mark 0x1/0x1;;
		oversea)
		${IPT_M} -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set --match-set oversea src -m dst -j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
		${IPT_M} -A SS_SPEC_TPROXY -p udp -m set --match-set gmlan src -m set -j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
		${IPT_M} -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set --match-set china_v4 dst -j TPROXY --on-port $LOCAL_PORT --tproxy-mark 0x01/0x01
		;;
		all)${IPT_M} -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -j TPROXY --on-port $LOCAL_PORT --tproxy-mark 0x1/0x1;;
	esac

	ipset -N by_all hash:net 2>/dev/null
	net=$(uci -qP /tmp/state get  network.wan.device) || net=$(uci -qP /tmp/state get network.wan.ifname)
	[ $net ] || net=127.0.0.1
	for i in $(ip -4 add show | grep -v $net | grep inet | grep -v 127.0.0.1 | awk '{print$2}');do
		ipset -! add by_all $i
	done

	${IPT_M} -I PREROUTING 1 -p udp $MATCH_SET -m set --match-set by_all src -m comment --comment "$TAG" -j SS_SPEC_TPROXY
	

}

gen_include(){
	extract_rules() {
		echo "*$1"
		iptables-save -t $1 | grep SS_SPEC | sed "s/^-A \(OUTPUT\|PREROUTING\)/-I \1 1/"
		echo 'COMMIT'
	}
	cat <<-EOF >> $FWI
	iptables-save -c | grep -v "SS_SPEC" | iptables-restore -c
	iptables-restore -n <<-EOT
	$(extract_rules nat)
	$(extract_rules mangle)
	EOT
EOF
	if [ $y ];then
		sed -i -e 's/-I PREROUTING 1 -p tcp/-I PREROUTING 2 -p tcp/' -e 's/PREROUTING 2 -p tcp -m set/PREROUTING 3 -p tcp -m set/' $FWI
		cat <<-EOF >> $FWI
	while ${IP6T_N} -D PREROUTING -p udp --dport 53 -m comment --comment $TAG -j REDIRECT --to-ports 53 2>/dev/null;do :;done
	while ${IP6T_N} -D PREROUTING -p tcp --dport 53 -m comment --comment $TAG -j REDIRECT --to-ports 53 2>/dev/null;do :;done
	[ -n "$ip6t" ] && ${IP6T_N} -I PREROUTING 1 -p udp --dport 53 -m comment --comment $TAG -j REDIRECT --to-ports 53
	[ -n "$ip6t" ] && ${IP6T_N} -I PREROUTING 2 -p tcp --dport 53 -m comment --comment $TAG -j REDIRECT --to-ports 53
EOF
	fi
}

while getopts ":s:l:S:L:N:P:a:b:w:p:G:D:rczyf" arg;do
	case $arg in
		s)server=$OPTARG;;
		l)local_port=$OPTARG;;
		S)SERVER=$OPTARG;;
		L)LOCAL_PORT=$OPTARG;;
		N)NF_SERVER=$OPTARG;;
		P)NF_PORT=$OPTARG;;
		a)LAN_AC_IP=$OPTARG;;
		b)WAN_BP_IP=$(for ip in $OPTARG;do echo $ip;done);;
		w)WAN_FW_IP=$OPTARG;;
		p)LAN_FP_IP=$OPTARG;;
		G)LAN_GM_IP=$OPTARG;;
		D)PROXY_PORTS=$OPTARG;;
		r)MODE=router;A=1;;
		c)MODE=oversea;A=1;;
		z)MODE=all;;
		y)y=1;;
		f)flush_r;exit 0;;
	esac
done

[ "$server" -a "$local_port" ] || exit 1
flush_r;ipset_r && tp_rule && gen_include || exit 1
