#!/bin/sh
NAME=bypass
S=/usr/share/$NAME

uci_get_by_name(){
	w=$(uci -q get $NAME.$1.$2)
	echo ${w:=$3}
}

uci_get_by_type(){
	w=$(uci -q get $NAME.@$1[0].$2)
	echo ${w:=$3}
}

log(){
	echo "$(date +'%Y-%m-%d %H:%M:%S') 自动切换检测： $*" >> /tmp/log/$NAME.log
}


get_ip(){
	i=0
	if ! echo $ip | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null;then
		r=1
		while ! nslookup $ip >/dev/null 2>&1;do
			[ $r -ge 10 ] && return 1 || let r++
			sleep 1
		done
		ip=$(nslookup $ip 2>/dev/null | grep Address | awk -F' ' '{print$NF}' | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$");i=$?
		ip=$(echo "$ip" | sed -n 1p)
	fi
	return $i
}

f_bin(){
	w=
	case $1 in
		ss)w=$(which ss-local);;
		ssr)w=$(which ssr-local);;
		v2ray)w=$(which xray)||w=$(which r2ray);;
		hysteria2)w=$(which hysteria);;
		trojan)w=$(which trojan-plus);;
		naiveproxy)w=$(which naive);;
	esac
	echo $w
}

gen_port(){
	lport=1090
	while [ $(netstat -tln | grep -c :$lport) != 0 ];do let lport++;done
}

gen_config_file(){
	pass=$(uci_get_by_name $1 password)
	timeout=$(uci_get_by_name $1 timeout 60)
	[ $(uci_get_by_name $1 fast_open 0) = 1 ] && fast=true || fast=false
	case $type in
		ss)
			cat <<-EOF > $J
{
"server":"$ip",
"server_port":$port,
"local_address":"0.0.0.0",
"local_port":$lport,
"password":"$pass",
"timeout":$timeout,
"method":"$(uci_get_by_name $1 encrypt_method_ss)",
"reuse_port":true,
"fast_open":$fast
}
EOF
			plugin=$(uci_get_by_name $1 plugin)
			if [ $plugin ];then
				sed -i "s@$ip\",@$ip\",\n\"plugin\":\"$plugin\",\n\"plugin_opts\":\"$(uci_get_by_name $1 plugin_opts)\",@" $J
			fi;;
		ssr)
			cat <<-EOF > $J
{
"server":"$ip",
"server_port":$port,
"local_address":"0.0.0.0",
"local_port":$lport,
"password":"$pass",
"timeout":$timeout,
"method":"$(uci_get_by_name $1 encrypt_method)",
"protocol":"$(uci_get_by_name $1 protocol)",
"protocol_param":"$(uci_get_by_name $1 protocol_param)",
"obfs":"$(uci_get_by_name $1 obfs)",
"obfs_param":"$(uci_get_by_name $1 obfs_param)",
"reuse_port":true,
"fast_open":$fast
}
EOF
;;
	naiveproxy)
		cat <<-EOF > $J
{
"listen":"socks://0.0.0.0:$lport",
"proxy":"https://$(uci_get_by_name $1 username):$pass@$(uci_get_by_name $1 server):$port",
"concurrency":"${3:-1}"
}
EOF
;;

	esac
}

curl_check(){
	if [ $(uci_get_by_name $1 kcp_enable 0) = 1 ];then
		log "Skip KCPTUN Node!";return 1
	fi
	type=$(uci_get_by_name $1 type)
	if [ $type = tun ];then
		curl --interface $(uci_get_by_name $1 iface br-lan) --resolve www.google.com:443:216.239.38.120 -so /dev/null --connect-timeout 20 https://www.google.com;i=$?
		[ $i = 0 ] || log "Server : $($UCI$1.alias || uci_get_by_name $1 server) cURL check error, Try to switch another server."
		return $i
	elif [ $type != socks5 ];then
		cmd=$(f_bin $type)
		if [ ! $cmd ];then
			[ $type = ss -o $type = ssr ] && type=$type-local
			log "Can't find $(echo $type) program, Skip this Node($($UCI$1.alias || uci_get_by_name $1 server))."
			return 1
		fi
	fi
	gen_port
	J=/var/etc/$NAME-check.json
	gen_config_file $1
	IP=127.0.0.1
	param=
	case $type in
		ss|ssr)
			$cmd -c $J >/dev/null 2>&1 &;;
		v2ray)
			$S/gen_xray $1 tcp 0 $lport $ip > $J
			sed -i 's/\\//g' $J
			$cmd run -config $J  >/dev/null 2>&1 &
			;;
		hysteria2)
			$S/gen_hysteria2 $1 tcp 0 $lport $ip >$J
			sed -i 's/\\//g' $J
			$cmd -c $J >/dev/null 2>&1 &;;
		trojan)
			$S/gen_config $1 client $lport $ip > $J
			sed -i 's/\\//g' $J
			$cmd --config $J >/dev/null 2>&1 &;;
		naiveproxy)
			$cmd $J 2>&1 &;;
		socks5)IP=$ip
			if [ $(uci_get_by_name $1 auth_enable 0) = 1 ];then
				username=$(uci_get_by_name $1 username)
				if [ -n "$username" ];then
					param="-U $username:$(uci_get_by_name $1 password)"
				else
					return 1
				fi
			fi;;
	esac
	r=1
	while [ $(netstat -tlnp | grep ${cmd##*/} | grep -c :$lport) = 0 ];do
		[ $r -ge 10 ] && return 1 || let r++
		sleep 1
	done
	curl -x socks5://$IP:$lport $param --resolve www.google.com:443:216.239.38.120 -so /dev/null --connect-timeout 20 https://www.google.com;i=$?
	kill -9 $(busybox ps -w | grep -v grep | grep $J  | awk '{print$1}') 2>/dev/null
	rm -f $J
	[ $i = 0 ] || log "Server : $($UCI$1.alias || uci_get_by_name $1 server) cURL check error, Try to switch another server."
	return $i
}

test_proxy(){
	ip=$(uci_get_by_name $1 server)
	get_ip || return 1
	port=$(uci_get_by_name $1 server_port)
	ipset add ss_spec_wan_ac $ip 2>/dev/null
	a=$?
	b=$(tcping -c $time_b -i 1 -t 2 -p $port $ip 2>/dev/null | grep 'failed' | awk -F ',' '{print$3}' | awk -F . '{print$1}')
	if [ -z "$b" -o "$b" -gt 50 ];then
		b=1
	else
		curl_check $1;b=$?
	fi
	[ $a = 0 ] && ipset del ss_spec_wan_ac $ip 2>/dev/null
	return $b
}

check_proxy(){
	for i in $(seq 1 $(uci_get_by_type global switch_try_count 3));do
		curl --connect-timeout $time_b -so /dev/null https://www.google.com/generate_204 && return 0
		a=2
		ping -c 3 -W 1 223.5.5.5 > /dev/null 2>&1
		[ $? -eq 0 ] &&	a=1
		sleep 1
	done
	return $a
}

select_proxy(){
	SERVER_C=0
	a=$(uci -X show $NAME | grep =servers)
	b=$(echo "$a" | wc -l)
	[ $c -ge $b ] && c=1
	for i in $(seq $c $b);do
		d=$(echo "$a" | sed 's/.*\.\(.*\)=.*/\1/' | sed -n ${i}p)
		([ $d = $SERVER_B ] || [ $(uci_get_by_name $d switch_enable 0) != 1 ]) && continue
		ip=$(uci_get_by_name $d server)
		get_ip || continue
		port=$(uci_get_by_name $d server_port)
		ipset add ss_spec_wan_ac $ip 2>/dev/null
		$S/by-check $ip $port $time_b
		local ret=$?
		ipset del ss_spec_wan_ac $ip 2>/dev/null
		if [ "$ret" == "0" ]; then
			SERVER_C=$d
			c=$i
			return 0
		fi

	done
}

switch_proxy(){
	/etc/init.d/$NAME restart $1
	return 0
}

[ "$1" = start ] || exit 1
SERVER_A=$(uci_get_by_type global global_server)
SERVER_B=$SERVER_A

SERVER_C=0
[ $(uci_get_by_name $SERVER_A kcp_enable 0) = 1 ] && return 1
c=1
time_a=$(uci_get_by_type global switch_time 300)
time_b=$(uci_get_by_type global switch_timeout 5)
UCI="uci -q get $NAME."
sleep 10
while :;do
	#检测主节点是否能使用
	check_proxy
	status=$?
	if [ "$status" == 2 ]; then
		log "无法连接到网络，请检查网络是否正常！"
		return 2
	fi

	if [ $SERVER_A != $SERVER_B ];then
		test_proxy $SERVER_A
		[ $? -eq 0 ] && {
			#主节点正常，切换到主节点
			log "${SERVER_A}主节点【$($UCI$SERVER_A.alias || uci_get_by_name $SERVER_A server)】正常，切换到主节点！"
			SERVER_B=$SERVER_A
			switch_proxy $SERVER_B
			[ $? -eq 0 ] && {
				log "【$($UCI$SERVER_B.alias || uci_get_by_name $SERVER_B server)】节点切换完毕！"
			}
			return 0
		}
	fi
		
	if [ "$status" == 0 ]; then
		return 0
	elif [ "$status" == "1" ]; then
	
		log "【$($UCI$SERVER_B.alias || uci_get_by_name $SERVER_B server) 】异常，切换到下一个节点！"
		select_proxy
		if [ $SERVER_C != 0 ];then
			SERVER_B=$SERVER_C
			log "$($UCI$SERVER_B.alias || uci_get_by_name $SERVER_B server) 正常，切换到此节点！"
			switch_proxy  $SERVER_B
		fi
	fi
	sleep $time_a
done
